# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparoksha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('Event_title', models.CharField(blank=True, max_length=512, null=True)),
                ('Event_desc', models.CharField(blank=True, max_length=512, null=True)),
                ('Event_date', models.DateTimeField()),
                ('Event_location', models.CharField(blank=True, max_length=512, null=True)),
                ('Event_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aparoksha.Users')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
